name: chat_web
description: A web app that uses AngularDart Components
version: 1.1.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0
  chat_api_client:
    path: ../chat_api_client
  angular_router: ^2.0.0-alpha
  web_socket_channel: ^1.1.0
  angular_forms: ^2.1.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_web_compilers: ^2.10.0
  build_test: ^1.0.0
  mockito: ^4.1.1
  pageloader: ^3.2.2
  sass_builder: ^2.1.3
  test: ^1.6.3
  webdev: ^2.5.4
