name: chat_web
description: A web app that uses AngularDart Components
version: 1.0.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  chat_api_client:
    path: ../chat_api_client
  angular_router: ^2.0.0-alpha+19
  web_socket_channel: ^1.0.9
  angular_forms: ^2.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  mockito: ^4.0.0
  pageloader: ^3.0.1
  sass_builder: ^2.1.2
  test: ^1.0.0
