name: chat_api
description: A starting point for Dart libraries or applications.
version: 2.0.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rest_api_server:
    git:
      url: https://gitlab.com/dartrest/rest_api_server.git
      ref: 2.2.3
  chat_models:
    path: ../chat_models
  shelf_web_socket: ^0.2.3
  web_socket_channel: ^1.1.0
dev_dependencies:
  test: ^1.15.2
  build_runner: ^1.10.0
