name: chat_api_client
description: Clients for chat application
version: 1.1.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rest_api_client:
    git:
      url: https://gitlab.com/dartrest/rest_api_client.git
      ref: '1.5.0'
  chat_models:
    path: ../chat_models
dev_dependencies:
  test: ^1.15.2
