name: chat_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rest_api_client:
    git:
      url: https://gitlab.com/dartrest/rest_api_client.git
      ref: 'master'
  chat_models:
    path: ../chat_models
dev_dependencies:
  test: ^1.0.0
